<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookingService.Domain\BookingService.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\packages\SharedContracts\SharedContracts.csproj" />
    <ProjectReference Include="..\..\..\..\packages\MessageClient\MessageClient.csproj" />
    <ProjectReference Include="..\..\..\..\packages\Exceptions\Exceptions\Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\Events\EventHandlers\" />
    <Folder Include="src\Events\Publishers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.5" />
    <PackageReference Include="OneOf" Version="3.0.271" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
