services:

  # ── Postgres Server ──────────────────────────────────────────────────────────────
  boking_db:
    image: postgres:16-alpine
    container_name: boking_db
    env_file: .env
    environment:
      POSTGRES_DB: ${BOOKING_DB}
      POSTGRES_USER: ${BOOKING_DB_USER}
      POSTGRES_PASSWORD: ${BOOKING_DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - bookingnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MSG_DB_USER} -d ${MSG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ── Redis ───────────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: booking-redis
    ports:
      - "6379:6379"
    volumes:
      - booking-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookingnetwork

  # ── Nginx ───────────────────────────────────────────────────────────────────
  nginx:
    image: nginx:alpine
    ports:
      - "5001:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - booking-api-1
    networks:
      - bookingnetwork

  # ── Booking API ─────────────────────────────────────────────────────────────
  booking-api-1: &api
    build:
      context: ../..
      dockerfile: apps/BookingService/Dockerfile
    env_file: .env
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=booking-db;Database=${BOOKING_DB};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis:6379"
    depends_on:
      booking-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bookingnetwork
  booking-api-2:
    <<: *api

networks:
  bookingnetwork:
    external: true

volumes:
  booking-db-data:
  booking-redis-data:
