<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InventoryService.Domain\InventoryService.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\packages\MessageClient\MessageClient.csproj" />
    <ProjectReference Include="..\..\..\..\packages\SharedContracts\SharedContracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
